import { generateMetadata } from '@/lib/seo'
import { getBreadcrumbSchema } from '@/lib/structured-data'
import Link from 'next/link'

export const metadata = generateMetadata({
  title: 'FAQ - YouTube Tools | Frequently Asked Questions',
  description: 'Find answers to common questions about our free YouTube tools. Learn how to download thumbnails, extract transcripts, and use our utilities effectively.',
  keywords: 'youtube tools faq, how to download youtube thumbnail, youtube transcript extractor help, youtube tools guide',
  canonical: 'https://tools.aipepal.com/faq',
})

const faqs = [
  {
    category: 'General',
    questions: [
      {
        q: 'Are all YouTube tools completely free?',
        a: 'Yes, all our YouTube tools are 100% free to use. There are no hidden costs, premium features, or registration requirements. We believe in providing valuable tools accessible to everyone.'
      },
      {
        q: 'Do I need to create an account to use the tools?',
        a: 'No account creation is required. All tools work instantly without any registration or sign-up process. Simply visit the tool page and start using it immediately.'
      },
      {
        q: 'Is my data safe when using these tools?',
        a: 'Absolutely. All processing happens locally in your browser. We don\'t store any personal information, YouTube URLs, or video data on our servers. Your privacy is our priority.'
      },
      {
        q: 'How often are the tools updated?',
        a: 'We regularly update our tools to ensure compatibility with YouTube\'s latest changes and to add new features based on user feedback. Updates are deployed automatically.'
      }
    ]
  },
  {
    category: 'Thumbnail Downloader',
    questions: [
      {
        q: 'What thumbnail qualities are available?',
        a: 'You can download YouTube thumbnails in multiple qualities: HD (1280x720), HQ (480x360), MQ (320x180), SD (120x90), and the maximum resolution thumbnail available for the video.'
      },
      {
        q: 'Can I download thumbnails from private videos?',
        a: 'No, thumbnails can only be downloaded from public YouTube videos. Private, unlisted, or region-restricted videos may not work with our tool.'
      },
      {
        q: 'What image formats are supported?',
        a: 'Thumbnails are downloaded in their original format, typically JPEG or WebP. The format depends on how YouTube stores the thumbnail for that specific video.'
      }
    ]
  },
  {
    category: 'Transcript Downloader',
    questions: [
      {
        q: 'What video types support transcript extraction?',
        a: 'Transcripts can be extracted from videos that have captions enabled - either auto-generated by YouTube or manually uploaded by the creator. Not all videos have transcripts available.'
      },
      {
        q: 'Can I download transcripts in different formats?',
        a: 'Yes, you can download transcripts in both TXT (plain text) and SRT (subtitle) formats. SRT files include timing information for each caption segment.'
      },
      {
        q: 'Are transcripts available in multiple languages?',
        a: 'If the video has captions in multiple languages, you can extract transcripts in any available language. Auto-translated captions are also supported where available.'
      },
      {
        q: 'How accurate are the extracted transcripts?',
        a: 'Transcript accuracy depends on the source. Manual captions are highly accurate, while auto-generated captions may contain errors, especially for technical terms or accented speech.'
      }
    ]
  },
  {
    category: 'Tags & Keywords',
    questions: [
      {
        q: 'How does the tags extractor work?',
        a: 'Our tags extractor analyzes YouTube video metadata to extract the tags and keywords used by the video creator. This helps with SEO research and competitive analysis.'
      },
      {
        q: 'Can I see tags from any YouTube video?',
        a: 'You can extract tags from most public YouTube videos. However, some creators may choose not to use tags, and private videos are not accessible.'
      },
      {
        q: 'How does the keyword generator create suggestions?',
        a: 'The keyword generator uses YouTube\'s autocomplete API and search suggestions to generate relevant keywords based on your input topic or seed keyword.'
      },
      {
        q: 'Are the generated keywords good for SEO?',
        a: 'Yes, the keywords are based on actual YouTube search data, making them valuable for video SEO, content planning, and understanding what users are searching for.'
      }
    ]
  },
  {
    category: 'Technical Issues',
    questions: [
      {
        q: 'Why isn\'t a tool working for a specific video?',
        a: 'Common issues include: the video is private/unlisted, region-restricted, has no captions (for transcripts), or the video ID is incorrect. Try with a different public video.'
      },
      {
        q: 'What browsers are supported?',
        a: 'Our tools work on all modern browsers including Chrome, Firefox, Safari, and Edge. We recommend using the latest version for the best experience.'
      },
      {
        q: 'Why am I getting a "rate limit" error?',
        a: 'To prevent abuse, we limit the number of requests per IP address. If you hit the limit, wait 15 minutes before trying again. The limit resets automatically.'
      },
      {
        q: 'Can I use these tools on mobile devices?',
        a: 'Yes, all our tools are fully responsive and work perfectly on smartphones and tablets. The interface adapts to your screen size for optimal usability.'
      }
    ]
  },
  {
    category: 'Legal & Compliance',
    questions: [
      {
        q: 'Is it legal to download YouTube thumbnails and transcripts?',
        a: 'Our tools access publicly available data through YouTube\'s standard interfaces. However, you should respect copyright laws and YouTube\'s terms of service when using downloaded content.'
      },
      {
        q: 'Can I use downloaded content commercially?',
        a: 'The legality depends on the original content\'s copyright status and your intended use. We recommend checking the video\'s license and getting permission from the content owner for commercial use.'
      },
      {
        q: 'Do you comply with GDPR and privacy regulations?',
        a: 'Yes, we don\'t collect personal data, use tracking cookies, or store user information. All processing happens locally in your browser, ensuring full privacy compliance.'
      }
    ]
  }
]

export default function FAQPage() {
  const breadcrumbSchema = getBreadcrumbSchema([
    { name: 'Home', url: 'https://tools.aipepal.com' },
    { name: 'FAQ', url: 'https://tools.aipepal.com/faq' },
  ])

  const faqSchema = {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: faqs.flatMap(category => 
      category.questions.map(faq => ({
        '@type': 'Question',
        name: faq.q,
        acceptedAnswer: {
          '@type': 'Answer',
          text: faq.a
        }
      }))
    )
  }

  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify(breadcrumbSchema),
        }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify(faqSchema),
        }}
      />
      <div className="min-h-screen bg-gradient-to-br from-slate-50 via-white to-blue-50">
        <header className="sticky top-0 z-50 backdrop-blur-xl bg-white/80 border-b border-gray-200/50">
          <nav className="container mx-auto px-4 py-4">
            <Link href="/" className="flex items-center space-x-3">
              <div className="w-10 h-10 bg-gradient-to-r from-red-500 to-red-600 rounded-xl flex items-center justify-center">
                <svg className="w-6 h-6 text-white" fill="currentColor" viewBox="0 0 24 24">
                  <path d="M23.498 6.186a3.016 3.016 0 0 0-2.122-2.136C19.505 3.545 12 3.545 12 3.545s-7.505 0-9.377.505A3.017 3.017 0 0 0 .502 6.186C0 8.07 0 12 0 12s0 3.93.502 5.814a3.016 3.016 0 0 0 2.122 2.136c1.871.505 9.376.505 9.376.505s7.505 0 9.377-.505a3.015 3.015 0 0 0 2.122-2.136C24 15.93 24 12 24 12s0-3.93-.502-5.814zM9.545 15.568V8.432L15.818 12l-6.273 3.568z"/>
                </svg>
              </div>
              <span className="text-xl font-bold">YouTube Tools</span>
            </Link>
          </nav>
        </header>

        <main className="container mx-auto px-4 py-12 max-w-6xl">
          <header className="text-center mb-16">
            <h1 className="text-5xl font-bold text-gray-900 mb-6">Frequently Asked Questions</h1>
            <p className="text-xl text-gray-600 max-w-3xl mx-auto">
              Find answers to common questions about our YouTube tools. Can't find what you're looking for? 
              <Link href="/contact" className="text-red-600 hover:text-red-700 ml-1">Contact us</Link>.
            </p>
          </header>

          <div className="space-y-12">
            {faqs.map((category, categoryIndex) => (
              <section key={categoryIndex} className="bg-white rounded-2xl shadow-lg p-8">
                <h2 className="text-3xl font-bold text-gray-900 mb-8 border-b border-gray-200 pb-4">
                  {category.category}
                </h2>
                <div className="space-y-6">
                  {category.questions.map((faq, faqIndex) => (
                    <article key={faqIndex} className="border-b border-gray-100 last:border-b-0 pb-6 last:pb-0">
                      <h3 className="text-lg font-semibold text-gray-900 mb-3">
                        {faq.q}
                      </h3>
                      <p className="text-gray-700 leading-relaxed">
                        {faq.a}
                      </p>
                    </article>
                  ))}
                </div>
              </section>
            ))}
          </div>

          <section className="mt-16 bg-gradient-to-r from-red-50 to-red-100 rounded-2xl p-8 text-center">
            <h2 className="text-2xl font-bold text-gray-900 mb-4">Still Have Questions?</h2>
            <p className="text-gray-700 mb-6">
              Our support team is here to help you get the most out of our YouTube tools.
            </p>
            <Link 
              href="/contact" 
              className="inline-flex items-center px-6 py-3 bg-red-600 text-white font-semibold rounded-xl hover:bg-red-700 transition-colors"
            >
              Contact Support
              <svg className="w-5 h-5 ml-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17 8l4 4m0 0l-4 4m4-4H3" />
              </svg>
            </Link>
          </section>
        </main>
      </div>
    </>
  )
}